server:
  port: 8080

eureka:
  client:
    fetch-registry: false # 禁止将自己作为客户端注册信息到Eureka服务器
    register-with-eureka: false # 禁止到Eureka器中获取注册信息
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/ # 告诉别人服务的注册和发现地址是这个 ${server.port}就是上面的8080
