spring:
  application:
    name: eureka-consumer

server:
    port: 8082

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/ # 服务的注册网址